name: attend
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.273
  flutter_svg: ^2.2.1
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.0
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  equatable: ^2.0.7
  mockito: ^5.6.1
  dartz: ^0.10.1
  logger: ^2.6.2
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  bloc: ^9.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.0-0.0.dev
  build_runner: ^2.10.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
